# Generated by Django 5.2.7 on 2025-10-16 09:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DopisovaSablona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, verbose_name='Název šablony')),
                ('predmet', models.CharField(max_length=200, verbose_name='Předmět dopisu')),
                ('text_muz', models.TextField(blank=True, help_text='Text dopisu pro muže', null=True, verbose_name='Text pro muže')),
                ('text_zena', models.TextField(blank=True, help_text='Text dopisu pro ženy', null=True, verbose_name='Text pro ženy')),
                ('editovatelna', models.BooleanField(default=False, help_text='Může operátor upravit text?', verbose_name='Editovatelná operátorem')),
            ],
            options={
                'verbose_name': 'Dopisová šablona',
                'verbose_name_plural': 'Dopisové šablony',
            },
        ),
        migrations.CreateModel(
            name='ProduktovaNabidka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název nabídky')),
                ('text', models.TextField(verbose_name='Text nabídky')),
                ('obrazek', models.ImageField(blank=True, null=True, upload_to='nabidky/', verbose_name='Obrázek produktu')),
            ],
            options={
                'verbose_name': 'Produktová nabídka',
                'verbose_name_plural': 'Produktové nabídky',
            },
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_2', models.CharField(blank=True, max_length=50, verbose_name='Zákaznické číslo')),
                ('info_3', models.CharField(blank=True, max_length=50, verbose_name='Přednostní číslo')),
                ('ansprache', models.CharField(blank=True, max_length=20, verbose_name='Oslovení (Pohlaví)')),
                ('titel', models.CharField(blank=True, max_length=20, verbose_name='Titul')),
                ('vorname', models.CharField(blank=True, max_length=100, verbose_name='Jméno')),
                ('nachname', models.CharField(blank=True, max_length=100, verbose_name='Příjmení')),
                ('dlbs', models.CharField(blank=True, max_length=50, verbose_name='Poslední objednávka')),
                ('info_1', models.CharField(blank=True, max_length=50, verbose_name='DBK')),
                ('telefon1', models.CharField(blank=True, max_length=30, verbose_name='Telefon 1')),
                ('telefon2', models.CharField(blank=True, max_length=30, verbose_name='Telefon 2')),
                ('geburtsdatum', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('datum_letztkontakt', models.CharField(blank=True, max_length=20, verbose_name='Poslední kontakt')),
                ('tlm_kampagne_2_zielprodukt', models.CharField(blank=True, max_length=100, verbose_name='Kampaň')),
                ('strasse', models.CharField(blank=True, max_length=100, verbose_name='Ulice')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Město')),
                ('plz', models.CharField(blank=True, max_length=20, verbose_name='Poštovní směrovací číslo')),
                ('recency', models.CharField(blank=True, max_length=20, verbose_name='Typ zákazníka')),
                ('vip', models.BooleanField(default=False, verbose_name='VIP kontakt')),
                ('vip_pridano', models.DateTimeField(blank=True, null=True, verbose_name='Do VIP přidáno dne')),
                ('vip_poznamka', models.TextField(blank=True, verbose_name='Interní poznámka k VIP')),
                ('trvale_blokovan', models.BooleanField(default=False, verbose_name='Trvale blokovaný kontakt')),
                ('nedovolano_pocet', models.PositiveIntegerField(default=0, verbose_name='Počet pokusů Nedovoláno')),
                ('odlozeny_nedovolano_pokusy', models.PositiveIntegerField(default=0, verbose_name='Počet pokusů Nedovoláno (odložené)')),
                ('blokace_do', models.DateTimeField(blank=True, null=True, verbose_name='Blokace do')),
                ('aktivni', models.BooleanField(default=True, verbose_name='Aktivní kontakt')),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Přiřazený operátor')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakty',
            },
        ),
        migrations.CreateModel(
            name='Korespondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('predmet', models.CharField(max_length=200, verbose_name='Předmět dopisu')),
                ('soubor', models.FileField(upload_to='dokumenty/', verbose_name='Soubor dopisu')),
                ('poznamka', models.TextField(blank=True, verbose_name='Poznámka')),
                ('kontakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korespondence', to='contacts.kontakt')),
            ],
            options={
                'verbose_name': 'Korespondence',
                'verbose_name_plural': 'Korespondence',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('operator_work', 'Běžná práce'), ('vip_interface', 'VIP Interface'), ('call_handling', 'Call Handling'), ('other', 'Other')], max_length=20, verbose_name='Typ akce')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Čas začátku')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Čas ukončení')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.kontakt', verbose_name='Kontakt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_actions', to=settings.AUTH_USER_MODEL, verbose_name='Operátor')),
            ],
            options={
                'verbose_name': 'Akce operátora',
                'verbose_name_plural': 'Akce operátorů',
            },
        ),
        migrations.CreateModel(
            name='Vratka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vratky', models.DateField(verbose_name='Datum vrácení')),
                ('duvod', models.CharField(blank=True, max_length=255, null=True, verbose_name='Důvod vrácení')),
                ('datum_importu', models.DateTimeField(auto_now_add=True, verbose_name='Datum importu')),
                ('agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agent')),
                ('cislo_faktury', models.CharField(blank=True, max_length=100, null=True, verbose_name='Číslo faktury')),
                ('datum_faktury', models.DateField(blank=True, null=True, verbose_name='Datum faktury')),
                ('castka_faktury', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Částka faktury')),
                ('castka_vratky', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Částka vratky')),
                ('kontakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vratky', to='contacts.kontakt', verbose_name='Kontakt')),
            ],
            options={
                'verbose_name': 'Vratka',
                'verbose_name_plural': 'Vratky',
                'ordering': ['-datum_vratky'],
            },
        ),
        migrations.CreateModel(
            name='UserDopisovaSablona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_muz', models.TextField(blank=True, null=True, verbose_name='Uživatelský text pro muže')),
                ('text_zena', models.TextField(blank=True, null=True, verbose_name='Uživatelský text pro ženy')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum poslední úpravy')),
                ('base_sablona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.dopisovasablona', verbose_name='Základní šablona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uživatel (operátor)')),
            ],
            options={
                'verbose_name': 'Uživatelská dopisová šablona',
                'verbose_name_plural': 'Uživatelské dopisové šablony',
                'unique_together': {('user', 'base_sablona')},
            },
        ),
    ]
