# Generated by Django 5.2.7 on 2025-10-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_kontakt_updated_at_alter_kontakt_assigned_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='info_2',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Zákaznické číslo'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='info_3',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Přednostní číslo'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='nachname',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Poslední aktualizace'),
        ),
    ]
