# Generated by Django 5.2.7 on 2025-10-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_kontakt_info_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_cas', models.DateTimeField(auto_now_add=True)),
                ('poznamka', models.TextField()),
                ('kontakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie', to='contacts.kontakt')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Záznam historie',
                'verbose_name_plural': 'Záznamy historie',
                'ordering': ['-datum_cas'],
            },
        ),
    ]
