# Generated by Django 5.2.7 on 2025-10-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_historie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dopisovasablona',
            name='text_muz',
            field=models.TextField(blank=True, default='', help_text='Text dopisu pro muže', verbose_name='Text pro muže'),
        ),
        migrations.AlterField(
            model_name='dopisovasablona',
            name='text_zena',
            field=models.TextField(blank=True, default='', help_text='Text dopisu pro ženy', verbose_name='Text pro ženy'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='ansprache',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Oslovení (Pohlaví)'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='datum_letztkontakt',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Poslední kontakt'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='dlbs',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Poslední objednávka'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='info_1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='DBK'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='info_3',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Přednostní číslo'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='nachname',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='ort',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='plz',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Poštovní směrovací číslo'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='recency',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Typ zákazníka'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='strasse',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='telefon1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Telefon 1'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='telefon2',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon 2'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Titul'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='tlm_kampagne_2_zielprodukt',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Kampaň'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='vip_poznamka',
            field=models.TextField(blank=True, default='', verbose_name='Interní poznámka k VIP'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='vorname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='userdopisovasablona',
            name='text_muz',
            field=models.TextField(blank=True, default='', verbose_name='Uživatelský text pro muže'),
        ),
        migrations.AlterField(
            model_name='userdopisovasablona',
            name='text_zena',
            field=models.TextField(blank=True, default='', verbose_name='Uživatelský text pro ženy'),
        ),
        migrations.AlterField(
            model_name='vratka',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='vratka',
            name='cislo_faktury',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Číslo faktury'),
        ),
        migrations.AlterField(
            model_name='vratka',
            name='duvod',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Důvod vrácení'),
        ),
    ]
