# Generated by Django 5.2.3 on 2025-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_dopisovasablona_text_muz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='datum_prirazeni',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum posledního přiřazení'),
        ),
    ]
