# Generated by Django 5.2.3 on 2025-10-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_historie_options_historie_naplanovany_hovor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historie',
            name='hodnota_objednavky',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hodnota objednávky'),
        ),
        migrations.AddField(
            model_name='historie',
            name='typ_akce',
            field=models.CharField(blank=True, choices=[('SPOJENY', 'Spojený hovor'), ('NESPOJENY', 'Nespojený hovor'), ('INTERNI', 'Interní akce')], max_length=20, null=True, verbose_name='Typ akce'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='nedovolano_v_rade',
            field=models.PositiveIntegerField(default=0, verbose_name="Počet 'Nedovoláno' v řadě"),
        ),
    ]
