# Generated by Django 5.2.7 on 2025-10-23 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_kontakt_deaktivovan_do'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='datum_importu',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Datum importu/aktualizace'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='datum_posledniho_prodeje',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum posledního prodeje'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Čas uzamčení'),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Dočasně uzamčeno operátorem'),
        ),
    ]
