# Generated by Django 5.2.3 on 2025-10-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprava', '0002_historicalcustomuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalcustomuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
