# Generated by Django 5.2.7 on 2025-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_kontakt_info_2_alter_kontakt_info_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='info_2',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True, verbose_name='Zákaznické číslo'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='telefon1',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Telefon 1'),
        ),
    ]
