# Generated by Django 5.2.7 on 2025-10-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_kontakt_info_2_alter_kontakt_telefon1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='info_2',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Zákaznické číslo'),
        ),
    ]
