# Generated by Django 5.2.3 on 2025-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_kontakt_datum_prirazeni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historie',
            options={},
        ),
        migrations.AddField(
            model_name='historie',
            name='naplanovany_hovor',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum naplánovaného hovoru'),
        ),
        migrations.AddField(
            model_name='historie',
            name='status',
            field=models.CharField(blank=True, choices=[('nedovolano', 'Nedovoláno'), ('nezajem', 'Nezájem'), ('neexistujici', 'Neexistující číslo/blokace'), ('nemluveno', 'Nemluveno s KO'), ('nerelevance', 'Nerelevance'), ('prodej', 'Prodej'), ('vip', 'Přidáno do VIP'), ('volat_pozdeji', 'Volat později'), ('predat_operatorovi', 'Předat na jiného operátora')], default='', max_length=20, verbose_name='Status hovoru'),
        ),
        migrations.AlterField(
            model_name='historie',
            name='poznamka',
            field=models.TextField(verbose_name='Poznámka k hovoru'),
        ),
    ]
