# Generated by Django 5.2.3 on 2025-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_historie_hodnota_objednavky_historie_typ_akce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='deaktivovan_do',
            field=models.DateField(blank=True, null=True, verbose_name='Deaktivován do'),
        ),
    ]
